source 'https://rubygems.org'

gem 'coffee-rails'
gem 'ember-rails'
gem 'ember-source', '~> 1.8.1'
gem 'emblem-rails'
gem 'emblem-source', '~> 0.3.18'
gem 'faker'
gem 'haml-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'rails_12factor', group: :production
gem 'pg'
gem 'puma'
gem 'rails', '~> 4.0.13'
gem 'sass-rails', '~> 4.0.5'
gem 'uglifier'
gem 'pry-rails'
