source 'https://rubygems.org'

gem 'coffee-rails'
gem 'ember-rails'
gem 'ember-source', '~> 1.8.1'
gem 'emblem-rails'
gem 'faker'
gem 'haml-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'rails_12factor'
gem 'pg'
gem 'puma'
gem 'rails', '4.0.12'
gem 'sass-rails'
gem 'uglifier'
gem 'pry-rails'
